apiVersion: v2
name: zitadel
description: A Helm chart for ZITADEL
type: application
appVersion: v2.71.4
version: 8.13.0
kubeVersion: '>= 1.21.0-0'
icon: https://zitadel.com/zitadel-logo-dark.svg
maintainers:
  - name: zitadel
    email: support@zitadel.com
    url: https://zitadel.com
