{{- if .Values.login.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: login-config-dotenv
  {{- with .Values.login.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "zitadel.login.labels" . | nindent 4 }}
data:
  .env: |-
    {{ .Values.login.configmapConfig | nindent 4 }}
{{- end }}
