{{- if include "deepCheck" (dict "root" .Values "path" (splitList "." "zitadel.configmapConfig.FirstInstance.Org.Machine")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "login.serviceAccountName" . }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
  {{- with .Values.login.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "login.serviceAccountName" . }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "login.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "login.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}
