{{ if .Values.login.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zitadel.login.fullname" . }}
  {{- if .Values.login.service }}
  {{- with .Values.login.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
    {{- with .Values.login.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.login.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.login.service.type "ClusterIP") }}
  clusterIP: {{ .Values.login.service.clusterIP }}
  {{- end }}
  {{- if and .Values.service.externalTrafficPolicy (eq .Values.login.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.login.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.login.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ regexReplaceAll "\\W+" .Values.service.protocol "-" }}-server
      {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
      appProtocol: {{ .Values.login.service.appProtocol }}
      {{- end }}
  selector:
    {{- include "zitade.login.selectorLabels" . | nindent 4 }}
{{- end }}
